### ISSUE TITLE
MultiDex Error

### ISSUE THREAD

**Issue by mehranabi** [alex31n/NoboButton#1]
Hello, I'm using AndroidUtilCode seperatly in my project and also using MultiDex option. When add your library in my project, Then i got 'MultiDex: Multiple dex files define Lcom/Blankj/utilcode/util/LogUtils' !

**Comment by alex31n** [comment]
Thank you for report the issue, Its may help you https://stackoverflow.com/questions/22851103/android-studio-gradle-error-multiple-dex-files-define

**Comment by mehranabi** [comment]
Thanks for your reply, It was my mistake and resolved by cleaning gradle caches.
