### ISSUE TITLE
How to link button of xml with Java?

### ISSUE THREAD

**Issue by wu110011** [alex31n/NoboButton#5]
I used below code,but it doesn't work.

【Java】
NoboButton button = new NoboButton(this);
button = findViewById(R.id.area_btn);
button.setText("Submit");

【XML】
<com.ornach.nobobutton.NoboButton
                        android:id="@+id/area_btn"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:padding="10dp"
                        android:layout_marginBottom="20dp"
                        android:layout_weight="0.3"
                       />

**Comment by alex31n** [comment]
Are you added dependency in Gradle? 
You can add text from xml by adding app:nb_text="Submit"
Please Try only one new NoboButton(this) or findViewById(R.id.area_btn)

【Java】
button = findViewById(R.id.area_btn);

【XML】
<com.ornach.nobobutton.NoboButton
android:id="@+id/area_btn"
app:nb_text="Submit"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:padding="10dp"
android:layout_marginBottom="20dp"
android:layout_weight="0.3"
/>

**Comment by wu110011** [comment]
I solved it which is work now.Thank you!
